### PR TITLE
Consolidate dependency management, add pyzotero package

### PR DESCRIPTION
**Pull request by koeaw**
**Describe your changes**
Switches package management to [Poetry](https://python-poetry.org/) only and adds new project dependency [pyzotero](https://pypi.org/project/pyzotero/) in the process.

This PR:
- updates the existing lock file (`poetry.lock`) in terms of formatting, style only – reorders packages, updates spelling of libraries
- removes files associated with dependency management done using Pipenv
- adds `pyzotero` as new dependency for projects which need to interact with/import data from Zotero

**Additional info**
**Not** included in this PR is an update to the project's README, which would be helpful especially for users new to Poetry/users switching to Poetry from other package management systems.

This PR _also_ does **not** deal with previously discussed changes to/config of (?) install locations of Git submodules (relevant when working with Docker).

**Related issues and PRs**
Resolves issue:
- #10

**Checklist (Replace the space in square brackets with a lowercase x for all that apply)**
- [x] My changes don't generate new warnings or errors
- [ ] My changes follow the project's code formatting rules and style guidelines
- [ ] I have commented my code with Docstrings and code comments, particularly complex, unusual or hard-to-read code
- [ ] I have updated the project documentation to reflect the changes I introduce
- [ ] I have added new unit tests or updated existing ones to demonstrate my changes works

### CODE REVIEW

**Comment by koeaw** [comment]
@gythaogg Since we discussed that we both needed to look into this, could you check out these changes and share if they work for you? I wasn't planning on getting ahead of you on this :laughing: but ran into the problem of needing some new deps available on the remote sooner than expected.

**Comment by koeaw** [comment]
Commenting so we don't merge the PR before that's done: also needs to be tested by @katharinawuensche

**Comment by koeaw** [comment]
@gythaogg @katharinawuensche There's some "approve" functionality for reviewers, so I assigned you both now – I'd say once you both have given it the go-ahead, we can merge the PR.

**Review by gythaogg — APPROVED** [review]
Sorry I couldn't do it sooner. Looks good and works for me!

**Review by katharinawuensche — APPROVED** [review]
Sorry that this took me a while. Works for me!

**Comment by koeaw** [comment]
Thanks, will merge this then!

**Pull request merged**
